name: Build firmwares for Charybdis keyboards with Blackpill (STM32F411)
on:
  push:
    branches:
      - charybdis-upstream-f411
    paths-ignore:
      - "**.md"

jobs:
  build-bastardkb:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - bastardkb/charybdis/3x5/u4
          - bastardkb/charybdis/3x5/f411
          - bastardkb/charybdis/4x6/u4
          - bastardkb/charybdis/4x6/f411
        keymap:
          - default
          - via

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
          submodules: true

      - name: Build
        id: build
        run: |
          qmk compile -kb ${{ matrix.keyboard }} -km ${{ matrix.keymap }}

          TARGET="$(echo "${{ matrix.keyboard }}" | sed 's#/#_#g')_${{ matrix.keymap }}"
          echo ::set-output name=artifact-name::${TARGET}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "${{ steps.build.outputs.artifact-name }}"
          path: |
            *.hex
            *.bin
        continue-on-error: true
